var mockIssuesList = module.exports = [
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13189",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13189/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13189/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13189/events",
    "html_url": "https://github.com/npm/npm/pull/13189",
    "id": 162371507,
    "number": 13189,
    "title": "Issue #13113: Docs: link to `npm-tag` from cli docs on tag is 404",
    "user": {
      "login": "macdonst",
      "id": 353180,
      "avatar_url": "https://avatars.githubusercontent.com/u/353180?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/macdonst",
      "html_url": "https://github.com/macdonst",
      "followers_url": "https://api.github.com/users/macdonst/followers",
      "following_url": "https://api.github.com/users/macdonst/following{/other_user}",
      "gists_url": "https://api.github.com/users/macdonst/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/macdonst/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/macdonst/subscriptions",
      "organizations_url": "https://api.github.com/users/macdonst/orgs",
      "repos_url": "https://api.github.com/users/macdonst/repos",
      "events_url": "https://api.github.com/users/macdonst/events{/privacy}",
      "received_events_url": "https://api.github.com/users/macdonst/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-27T04:18:29Z",
    "updated_at": "2016-06-27T04:18:29Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/npm/npm/pulls/13189",
      "html_url": "https://github.com/npm/npm/pull/13189",
      "diff_url": "https://github.com/npm/npm/pull/13189.diff",
      "patch_url": "https://github.com/npm/npm/pull/13189.patch"
    },
    "body": "User @SimenB found a broken link. I think that the `npm-tag(3)` should actually be `npm-dist-tag(1)` in the see also section to link to the non-deprecated command."
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13185",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13185/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13185/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13185/events",
    "html_url": "https://github.com/npm/npm/issues/13185",
    "id": 162358555,
    "number": 13185,
    "title": "???,,,",
    "user": {
      "login": "DarylRoberts",
      "id": 11254990,
      "avatar_url": "https://avatars.githubusercontent.com/u/11254990?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DarylRoberts",
      "html_url": "https://github.com/DarylRoberts",
      "followers_url": "https://api.github.com/users/DarylRoberts/followers",
      "following_url": "https://api.github.com/users/DarylRoberts/following{/other_user}",
      "gists_url": "https://api.github.com/users/DarylRoberts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DarylRoberts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DarylRoberts/subscriptions",
      "organizations_url": "https://api.github.com/users/DarylRoberts/orgs",
      "repos_url": "https://api.github.com/users/DarylRoberts/repos",
      "events_url": "https://api.github.com/users/DarylRoberts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DarylRoberts/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-27T01:12:26Z",
    "updated_at": "2016-06-27T01:13:30Z",
    "closed_at": null,
    "body": "# \r\n\r\n- [x] `\r\n\r\n\r\n\r\n<!--`\r\n\r\n    Thank you for contributing to npm! Please review this checklist\r\n    before submitting your issue.\r\n\r\n    - Please check if there's a solution in the troubleshooting wiki:\r\n      https://github.com/npm/npm/wiki/Troubleshooting\r\n\r\n    - Also ensure that your new issue conforms to npm's contribution guidelines:\r\n      https://github.com/npm/npm/wiki/Contributing-Guidelines\r\n\r\n    - Participation in this open source project is subject to the npm Code of Conduct:\r\n      https://www.npmjs.com/policies/conduct\r\n\r\n    If you're here to provide a feature request, uncomment the final block below.\r\n-->\r\n\r\n### I'm opening this issue because:\r\n\r\n  \r\n\r\n\r\n- [ ] npm is crashing\r\n \r\n\r\n\r\n\r\n - [ ] npm is producing an incorrect install\r\n  - [ ] npm is doing something I don't understand\r\n  - [ ] other (_see below for feature requests_)\r\n\r\n#### Node version:\r\n\r\n<!-- output of 'node -v' -->\r\n\r\n#### npm version:\r\n\r\n<!-- output of 'npm -v' -->\r\n\r\n#### How did you install Node and npm?\r\n\r\n<!-- nodejs.org installer, Homebrew, apt-get -->\r\n\r\n#### Operating system version and distribution:\r\n\r\n<!--\r\n    operating systems: Linux, Windows 7, Windows 10, OS X 10.11.5, SmartOS\r\n    distributions: Ubuntu, Arch\r\n    ('uname -a' output is also helpful here, on non-Windows systems)\r\n-->\r\n\r\n#### Containerization or virtualization environment:\r\n\r\n<!-- Docker, Vagrant on Windows, Triton, Heroku, VirtualBox, Azure -->\r\n\r\n#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?\r\n\r\n#### What problem are you seeing?\r\n\r\n#### How can the problem be reproduced?\r\n\r\n<!--\r\n    Please provide minimal steps to reproducing the problem.\r\n    Include a gist of your npm-debug.log file.\r\n    If you've never used gist, read here:\r\n     https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log\r\n-->\r\n\r\n<!--\r\n    For feature requests, delete the above and uncomment the section following this one.\r\n\r\n    But first, take a look at the existing feature requests:\r\n      https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Aalready-looked-at\r\n-->\r\n\r\n<!--\r\n\r\n#### What's the feature?\r\n\r\n#### What problem is the feature intended to solve?\r\n\r\n#### Is the absence of this feature blocking you or your team? If so, how?\r\n\r\n#### Is this feature similar to an existing feature in another tool?\r\n\r\n#### Is this a feature you're prepared to implement, with support from the npm CLI team?\r\n\r\n-->\r\nHow can the problem be reproduced?"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13181",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13181/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13181/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13181/events",
    "html_url": "https://github.com/npm/npm/issues/13181",
    "id": 162336841,
    "number": 13181,
    "title": "Getting error while installing yo generator",
    "user": {
      "login": "ginnaskuttery",
      "id": 20150074,
      "avatar_url": "https://avatars.githubusercontent.com/u/20150074?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ginnaskuttery",
      "html_url": "https://github.com/ginnaskuttery",
      "followers_url": "https://api.github.com/users/ginnaskuttery/followers",
      "following_url": "https://api.github.com/users/ginnaskuttery/following{/other_user}",
      "gists_url": "https://api.github.com/users/ginnaskuttery/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ginnaskuttery/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ginnaskuttery/subscriptions",
      "organizations_url": "https://api.github.com/users/ginnaskuttery/orgs",
      "repos_url": "https://api.github.com/users/ginnaskuttery/repos",
      "events_url": "https://api.github.com/users/ginnaskuttery/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ginnaskuttery/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-26T17:05:30Z",
    "updated_at": "2016-06-26T17:05:30Z",
    "closed_at": null,
    "body": "Hello,\r\nI am not able to install yo generator. I have installed node and npm successfully.\r\nBut while installing yo getting error find the attached for error log.\r\nPlease help on this.\r\n\r\nThanks\r\nGinnas\r\n\r\n\r\n[npm-debug.TXT](https://github.com/npm/npm/files/333694/npm-debug.TXT)\r\n\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13179",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13179/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13179/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13179/events",
    "html_url": "https://github.com/npm/npm/issues/13179",
    "id": 162292725,
    "number": 13179,
    "title": "npm publish returns `Unexpected token < in JSON at position 1`",
    "user": {
      "login": "ajhyndman",
      "id": 11449340,
      "avatar_url": "https://avatars.githubusercontent.com/u/11449340?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ajhyndman",
      "html_url": "https://github.com/ajhyndman",
      "followers_url": "https://api.github.com/users/ajhyndman/followers",
      "following_url": "https://api.github.com/users/ajhyndman/following{/other_user}",
      "gists_url": "https://api.github.com/users/ajhyndman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ajhyndman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ajhyndman/subscriptions",
      "organizations_url": "https://api.github.com/users/ajhyndman/orgs",
      "repos_url": "https://api.github.com/users/ajhyndman/repos",
      "events_url": "https://api.github.com/users/ajhyndman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ajhyndman/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-25T18:01:44Z",
    "updated_at": "2016-06-25T18:01:44Z",
    "closed_at": null,
    "body": "<!--\r\n    Thank you for contributing to npm! Please review this checklist\r\n    before submitting your issue.\r\n\r\n    - Please check if there's a solution in the troubleshooting wiki:\r\n      https://github.com/npm/npm/wiki/Troubleshooting\r\n\r\n    - Also ensure that your new issue conforms to npm's contribution guidelines:\r\n      https://github.com/npm/npm/wiki/Contributing-Guidelines\r\n\r\n    - Participation in this open source project is subject to the npm Code of Conduct:\r\n      https://www.npmjs.com/policies/conduct\r\n\r\n    If you're here to provide a feature request, uncomment the final block below.\r\n-->\r\n\r\n### I'm opening this issue because:\r\n\r\n  - [ ] npm is crashing\r\n  - [ ] npm is producing an incorrect install\r\n  - [x] npm is doing something I don't understand\r\n  - [ ] other (_see below for feature requests_)\r\n\r\n#### Node version:\r\n\r\n`v6.2.2`\r\n\r\n#### npm version:\r\n\r\n`3.9.5`\r\n\r\n#### How did you install Node and npm?\r\n\r\nI ran a clean install on two machines today via `nvm install 6`.\r\n\r\n#### Operating system version and distribution:\r\n\r\n* `Linux ARANATHA 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux`\r\n* OS X El Capitan 10.11.5\r\n\r\n#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?\r\n\r\nI'm connecting directly via a home ADSL 2+ connection, in Sydney, Australia.\r\n\r\n#### What problem are you seeing?\r\n\r\n[npm-debug.txt](https://github.com/npm/npm/files/333200/npm-debug.txt)\r\n\r\nI've spent a few hours debugging, and my best guesses are:\r\n* My network connection is too slow and npm's servers are timing out on the request.  :(\r\n* npm's Sydney registry server is experiencing service outages.\r\n\r\nMy network stats:\r\n<a href=\"http://www.speedtest.net/my-result/5431131661\"><img src=\"http://www.speedtest.net/result/5431131661.png\" /></a>\r\n\r\nHere are a couple links to related issues that I've come across:\r\n* https://github.com/npm/npm/issues/5027 (from 2014)\r\n* https://github.com/npm/npm/issues/4400 (from 2013)\r\n\r\n<!--\r\n    Please provide minimal steps to reproducing the problem.\r\n    Include a gist of your npm-debug.log file.\r\n    If you've never used gist, read here:\r\n     https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log\r\n-->\r\n\r\n<!--\r\n    For feature requests, delete the above and uncomment the section following this one.\r\n\r\n    But first, take a look at the existing feature requests:\r\n      https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Aalready-looked-at\r\n-->\r\n\r\n<!--\r\n\r\n#### What's the feature?\r\n\r\n#### What problem is the feature intended to solve?\r\n\r\n#### Is the absence of this feature blocking you or your team? If so, how?\r\n\r\n#### Is this feature similar to an existing feature in another tool?\r\n\r\n#### Is this a feature you're prepared to implement, with support from the npm CLI team?\r\n\r\n-->\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13178",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13178/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13178/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13178/events",
    "html_url": "https://github.com/npm/npm/issues/13178",
    "id": 162278794,
    "number": 13178,
    "title": "EBUSY:resource busy or locked, open c:\\users\\user\\NTUSER.DAT ",
    "user": {
      "login": "ArunaLanda",
      "id": 20140656,
      "avatar_url": "https://avatars.githubusercontent.com/u/20140656?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ArunaLanda",
      "html_url": "https://github.com/ArunaLanda",
      "followers_url": "https://api.github.com/users/ArunaLanda/followers",
      "following_url": "https://api.github.com/users/ArunaLanda/following{/other_user}",
      "gists_url": "https://api.github.com/users/ArunaLanda/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ArunaLanda/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ArunaLanda/subscriptions",
      "organizations_url": "https://api.github.com/users/ArunaLanda/orgs",
      "repos_url": "https://api.github.com/users/ArunaLanda/repos",
      "events_url": "https://api.github.com/users/ArunaLanda/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ArunaLanda/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-25T12:20:21Z",
    "updated_at": "2016-06-25T12:23:04Z",
    "closed_at": null,
    "body": "<!--\r\n    Thank you for contributing to npm! Please review this checklist\r\n    before submitting your issue.\r\n\r\n    - Please check if there's a solution in the troubleshooting wiki:\r\n      https://github.com/npm/npm/wiki/Troubleshooting\r\n\r\n    - Also ensure that your new issue conforms to npm's contribution guidelines:\r\n      https://github.com/npm/npm/wiki/Contributing-Guidelines\r\n\r\n    - Participation in this open source project is subject to the npm Code of Conduct:\r\n      https://www.npmjs.com/policies/conduct\r\n\r\n    If you're here to provide a feature request, uncomment the final block below.\r\n-->\r\n\r\n### I'm opening this issue because:\r\n\r\n  - [ ] npm is crashing\r\n  - [ ] npm is producing an incorrect install\r\n  - [x] npm is doing something I don't understand\r\n  - [ ] other (_see below for feature requests_)\r\n\r\n#### Node version:\r\n\r\n<!-- output of 'node -v' -->\r\n\r\n#### npm version:\r\n\r\n<!-- output of 'npm -v' -->\r\n\r\n#### How did you install Node and npm?\r\n\r\n<!-- nodejs.org installer, Homebrew, apt-get -->\r\n\r\n#### Operating system version and distribution:\r\n\r\n<!--\r\n    operating systems: Linux, Windows 7, Windows 10, OS X 10.11.5, SmartOS\r\n    distributions: Ubuntu, Arch\r\n    ('uname -a' output is also helpful here, on non-Windows systems)\r\n-->\r\n\r\n#### Containerization or virtualization environment:\r\n\r\n<!-- Docker, Vagrant on Windows, Triton, Heroku, VirtualBox, Azure -->\r\n\r\n#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?\r\n\r\n#### What problem are you seeing?\r\n\r\n#### How can the problem be reproduced?\r\n\r\n<!--\r\n    Please provide minimal steps to reproducing the problem.\r\n    Include a gist of your npm-debug.log file.\r\n    If you've never used gist, read here:\r\n     https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log\r\n-->\r\n\r\n<!--\r\n    For feature requests, delete the above and uncomment the section following this one.\r\n\r\n    But first, take a look at the existing feature requests:\r\n      https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Aalready-looked-at\r\n-->\r\n\r\n<!--\r\n\r\n#### What's the feature?\r\n\r\n#### What problem is the feature intended to solve?\r\n\r\n#### Is the absence of this feature blocking you or your team? If so, how?\r\n\r\n#### Is this feature similar to an existing feature in another tool?\r\n\r\n#### Is this a feature you're prepared to implement, with support from the npm CLI team?\r\n\r\n-->\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13177",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13177/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13177/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13177/events",
    "html_url": "https://github.com/npm/npm/issues/13177",
    "id": 162278113,
    "number": 13177,
    "title": "Issue Linux 4.1.18+",
    "user": {
      "login": "MelloXVI",
      "id": 11180661,
      "avatar_url": "https://avatars.githubusercontent.com/u/11180661?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MelloXVI",
      "html_url": "https://github.com/MelloXVI",
      "followers_url": "https://api.github.com/users/MelloXVI/followers",
      "following_url": "https://api.github.com/users/MelloXVI/following{/other_user}",
      "gists_url": "https://api.github.com/users/MelloXVI/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MelloXVI/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MelloXVI/subscriptions",
      "organizations_url": "https://api.github.com/users/MelloXVI/orgs",
      "repos_url": "https://api.github.com/users/MelloXVI/repos",
      "events_url": "https://api.github.com/users/MelloXVI/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MelloXVI/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-25T12:00:18Z",
    "updated_at": "2016-06-26T13:50:56Z",
    "closed_at": null,
    "body": "After this command : `npm run start`\r\n\r\n\r\n```\r\nnpm ERR! Linux 4.1.18+\r\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"run\" \"start\"\r\nnpm ERR! node v4.2.1\r\nnpm ERR! npm  v2.14.7\r\n\r\nnpm ERR! missing script: start\r\nnpm ERR!\r\nnpm ERR! If you need help, you may report this error at:\r\nnpm ERR!     <https://github.com/npm/npm/issues>\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     /home/pi/homebridge/npm-debug.log\r\n\r\n```\r\nHello, I've this ussue. Have you got any idea about that ? \r\nIn \"npm-debug.log\"\r\n```\r\n0 info it worked if it ends with ok\r\n1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]\r\n2 info using npm@2.14.7\r\n3 info using node@v4.2.1\r\n4 verbose stack Error: missing script: start\r\n4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:1$\r\n4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5\r\n4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-packag$\r\n4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modul$\r\n4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)\r\n5 verbose cwd /home/pi/homebridge\r\n6 error Linux 4.1.18+\r\n7 error argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"run\" \"start\"\r\n8 error node v4.2.1\r\n9 error npm  v2.14.7\r\n10 error missing script: start\r\n11 error If you need help, you may report this error at:\r\n11 error     <https://github.com/npm/npm/issues>\r\n12 verbose exit [ 1, true ]\r\n```\r\n\r\n\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13174",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13174/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13174/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13174/events",
    "html_url": "https://github.com/npm/npm/issues/13174",
    "id": 162265754,
    "number": 13174,
    "title": "npm run can fail if abs path of packages.json contains colon",
    "user": {
      "login": "chulkilee",
      "id": 69235,
      "avatar_url": "https://avatars.githubusercontent.com/u/69235?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chulkilee",
      "html_url": "https://github.com/chulkilee",
      "followers_url": "https://api.github.com/users/chulkilee/followers",
      "following_url": "https://api.github.com/users/chulkilee/following{/other_user}",
      "gists_url": "https://api.github.com/users/chulkilee/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chulkilee/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chulkilee/subscriptions",
      "organizations_url": "https://api.github.com/users/chulkilee/orgs",
      "repos_url": "https://api.github.com/users/chulkilee/repos",
      "events_url": "https://api.github.com/users/chulkilee/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chulkilee/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-25T05:50:31Z",
    "updated_at": "2016-06-25T05:50:31Z",
    "closed_at": null,
    "body": "**This is not a bug of NPM but a limitation of how `$PATH` works. Leave this note to let others to avoid spending time on it 😄** Probably better to put this in wiki, but I do not have permission to edit wiki pages.\r\n\r\n* `npm run` add absolute path of `node_modules/.bin` to `$PATH`.\r\n* `$PATH` uses colon (`:`) as separator\r\n* It is possible to put `:` in a directory name\r\n\r\nAs a result, if absolute path of your `node_modules/.bin` contains `:` somewhere, `npm run x` can fail if it uses executable in the `node_modules/.bin`.  For example, if you use `gulp` then it will show an error: `sh: gulp: command not found`.\r\n\r\nTo avoid this problem, do not use colon (`:`) in directory name.\r\n\r\nNote: if you're using Mac, if you create a new directory with slash in Finder, it is shown as `:` in command line although you see `/` in Finder."
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13173",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13173/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13173/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13173/events",
    "html_url": "https://github.com/npm/npm/issues/13173",
    "id": 162258239,
    "number": 13173,
    "title": "npm install error",
    "user": {
      "login": "sagar2503",
      "id": 8601444,
      "avatar_url": "https://avatars.githubusercontent.com/u/8601444?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sagar2503",
      "html_url": "https://github.com/sagar2503",
      "followers_url": "https://api.github.com/users/sagar2503/followers",
      "following_url": "https://api.github.com/users/sagar2503/following{/other_user}",
      "gists_url": "https://api.github.com/users/sagar2503/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sagar2503/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sagar2503/subscriptions",
      "organizations_url": "https://api.github.com/users/sagar2503/orgs",
      "repos_url": "https://api.github.com/users/sagar2503/repos",
      "events_url": "https://api.github.com/users/sagar2503/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sagar2503/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-25T02:16:34Z",
    "updated_at": "2016-06-25T02:16:34Z",
    "closed_at": null,
    "body": "<!--\r\n    Thank you for contributing to npm! Please review this checklist\r\n    before submitting your issue.\r\n\r\n    - Please check if there's a solution in the troubleshooting wiki:\r\n      https://github.com/npm/npm/wiki/Troubleshooting\r\n\r\n    - Also ensure that your new issue conforms to npm's contribution guidelines:\r\n      https://github.com/npm/npm/wiki/Contributing-Guidelines\r\n\r\n    - Participation in this open source project is subject to the npm Code of Conduct:\r\n      https://www.npmjs.com/policies/conduct\r\n\r\n    If you're here to provide a feature request, uncomment the final block below.\r\n-->\r\n\r\n### I'm opening this issue because:\r\n\r\n  - [X] npm is crashing\r\n  - [ ] npm is producing an incorrect install\r\n  - [ ] npm is doing something I don't understand\r\n  - [ ] other (_see below for feature requests_)\r\n\r\n#### Node version:node v4.2.2\r\n\r\n<!-- output of 'node -v' -->\r\n\r\n#### npm version:npm  v2.14.7\r\n[NPM INTALL ERROR.txt](https://github.com/npm/npm/files/332865/NPM.INTALL.ERROR.txt)\r\n\r\n<!-- output of 'npm -v' -->\r\n\r\n#### How did you install Node and npm?\r\n\r\n<!-- nodejs.org installer, Homebrew, apt-get -->\r\n\r\n#### Operating system version and distribution: Windows_NT 6.1.7601\r\n\r\n<!--\r\n    operating systems: Linux, Windows 7, Windows 10, OS X 10.11.5, SmartOS\r\n    distributions: Ubuntu, Arch\r\n    ('uname -a' output is also helpful here, on non-Windows systems)\r\n-->\r\n\r\n#### Containerization or virtualization environment:\r\n\r\n<!-- Docker, Vagrant on Windows, Triton, Heroku, VirtualBox, Azure -->\r\n\r\n#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?\r\n\r\n#### What problem are you seeing?\r\n\r\n#### How can the problem be reproduced?\r\n\r\n<!--\r\n    Please provide minimal steps to reproducing the problem.\r\n    Include a gist of your npm-debug.log file.\r\n    If you've never used gist, read here:\r\n     https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log\r\n-->\r\n\r\n<!--\r\n    For feature requests, delete the above and uncomment the section following this one.\r\n\r\n    But first, take a look at the existing feature requests:\r\n      https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Aalready-looked-at\r\n-->\r\n\r\n<!--\r\n\r\n#### What's the feature?\r\n\r\n#### What problem is the feature intended to solve?\r\n\r\n#### Is the absence of this feature blocking you or your team? If so, how?\r\n\r\n#### Is this feature similar to an existing feature in another tool?\r\n\r\n#### Is this a feature you're prepared to implement, with support from the npm CLI team?\r\n\r\n-->\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13172",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13172/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13172/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13172/events",
    "html_url": "https://github.com/npm/npm/issues/13172",
    "id": 162224925,
    "number": 13172,
    "title": "too slow to search for packages",
    "user": {
      "login": "justin-romano",
      "id": 1707226,
      "avatar_url": "https://avatars.githubusercontent.com/u/1707226?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/justin-romano",
      "html_url": "https://github.com/justin-romano",
      "followers_url": "https://api.github.com/users/justin-romano/followers",
      "following_url": "https://api.github.com/users/justin-romano/following{/other_user}",
      "gists_url": "https://api.github.com/users/justin-romano/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/justin-romano/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/justin-romano/subscriptions",
      "organizations_url": "https://api.github.com/users/justin-romano/orgs",
      "repos_url": "https://api.github.com/users/justin-romano/repos",
      "events_url": "https://api.github.com/users/justin-romano/events{/privacy}",
      "received_events_url": "https://api.github.com/users/justin-romano/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/npm/npm/labels/search",
        "name": "search",
        "color": "6A31CA"
      },
      {
        "url": "https://api.github.com/repos/npm/npm/labels/support",
        "name": "support",
        "color": "000000"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-24T20:28:56Z",
    "updated_at": "2016-06-25T01:46:07Z",
    "closed_at": null,
    "body": "This is for the website mainly. But it is way to slow to search. I would expect to get results back sub second. "
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13171",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13171/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13171/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13171/events",
    "html_url": "https://github.com/npm/npm/issues/13171",
    "id": 162211471,
    "number": 13171,
    "title": "Does npminclude still exist?",
    "user": {
      "login": "mapsam",
      "id": 1943001,
      "avatar_url": "https://avatars.githubusercontent.com/u/1943001?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mapsam",
      "html_url": "https://github.com/mapsam",
      "followers_url": "https://api.github.com/users/mapsam/followers",
      "following_url": "https://api.github.com/users/mapsam/following{/other_user}",
      "gists_url": "https://api.github.com/users/mapsam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mapsam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mapsam/subscriptions",
      "organizations_url": "https://api.github.com/users/mapsam/orgs",
      "repos_url": "https://api.github.com/users/mapsam/repos",
      "events_url": "https://api.github.com/users/mapsam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mapsam/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-24T19:09:17Z",
    "updated_at": "2016-06-24T19:09:17Z",
    "closed_at": null,
    "body": "Hey! I am looking at packaging some `.hpp` files in a package, and want to ignore a bunch of related build files in the `.npmignore` file, which falls out of sync quickly. I searched for `.npminclude` and see it was [implemented a long time ago](https://github.com/npm/npm/issues/94). I tried using `npm pack` to test it out, but no luck. Is there still support for `.npminclude` files?\r\n\r\nnpm version: `2.15.5`"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13170",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13170/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13170/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13170/events",
    "html_url": "https://github.com/npm/npm/issues/13170",
    "id": 162196170,
    "number": 13170,
    "title": "atlas-connect install error",
    "user": {
      "login": "sonnymyet",
      "id": 17376571,
      "avatar_url": "https://avatars.githubusercontent.com/u/17376571?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sonnymyet",
      "html_url": "https://github.com/sonnymyet",
      "followers_url": "https://api.github.com/users/sonnymyet/followers",
      "following_url": "https://api.github.com/users/sonnymyet/following{/other_user}",
      "gists_url": "https://api.github.com/users/sonnymyet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sonnymyet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sonnymyet/subscriptions",
      "organizations_url": "https://api.github.com/users/sonnymyet/orgs",
      "repos_url": "https://api.github.com/users/sonnymyet/repos",
      "events_url": "https://api.github.com/users/sonnymyet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sonnymyet/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-24T17:42:16Z",
    "updated_at": "2016-06-26T13:56:58Z",
    "closed_at": null,
    "body": "Hi I'm having error installing atlas-connect tool. Not sure if i'm posting at the right place tho but help would be very much appreciated. \r\n\r\n[npm-debug.txt](https://github.com/npm/npm/files/332213/npm-debug.txt)\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13169",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13169/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13169/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13169/events",
    "html_url": "https://github.com/npm/npm/issues/13169",
    "id": 162139608,
    "number": 13169,
    "title": "npm install -g cordova error",
    "user": {
      "login": "kzpromo",
      "id": 10184174,
      "avatar_url": "https://avatars.githubusercontent.com/u/10184174?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kzpromo",
      "html_url": "https://github.com/kzpromo",
      "followers_url": "https://api.github.com/users/kzpromo/followers",
      "following_url": "https://api.github.com/users/kzpromo/following{/other_user}",
      "gists_url": "https://api.github.com/users/kzpromo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kzpromo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kzpromo/subscriptions",
      "organizations_url": "https://api.github.com/users/kzpromo/orgs",
      "repos_url": "https://api.github.com/users/kzpromo/repos",
      "events_url": "https://api.github.com/users/kzpromo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kzpromo/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-24T12:47:43Z",
    "updated_at": "2016-06-25T21:38:45Z",
    "closed_at": null,
    "body": "error log\r\n[npm-debug.log.txt](https://github.com/npm/npm/files/331749/npm-debug.log.txt)\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13168",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13168/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13168/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13168/events",
    "html_url": "https://github.com/npm/npm/issues/13168",
    "id": 162090915,
    "number": 13168,
    "title": "Unable to install from GitHub URL in package.json",
    "user": {
      "login": "HouCoder",
      "id": 5292143,
      "avatar_url": "https://avatars.githubusercontent.com/u/5292143?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HouCoder",
      "html_url": "https://github.com/HouCoder",
      "followers_url": "https://api.github.com/users/HouCoder/followers",
      "following_url": "https://api.github.com/users/HouCoder/following{/other_user}",
      "gists_url": "https://api.github.com/users/HouCoder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HouCoder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HouCoder/subscriptions",
      "organizations_url": "https://api.github.com/users/HouCoder/orgs",
      "repos_url": "https://api.github.com/users/HouCoder/repos",
      "events_url": "https://api.github.com/users/HouCoder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HouCoder/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2016-06-24T07:24:58Z",
    "updated_at": "2016-06-27T04:28:08Z",
    "closed_at": null,
    "body": "**Environment:**\r\n\r\nNode version: `v0.10.42`\r\nNpm version: `1.3.6`\r\nOS: `CentOS release 6.5 (Final)`\r\n\r\n**Issue detail:**\r\n\r\nIn [package.json | npm Documentation#GitHub URLs](https://docs.npmjs.com/files/package.json#github-urls), it says:\r\n\r\n> As of version 1.1.65, you can refer to GitHub urls as just \"foo\": \"user/foo-project\".\r\n\r\nI tried `$ npm install juwai/juwai-lint-cfg` and it completed successfully, then I add `\"juwai-lint-cfg\": \"juwai/juwai-lint-cfg\"` in my package.json and did `$ npm install`, however it fails with this error message:\r\n\r\n```shell\r\n[vagrant@vagrant-centos65 test]$ npm install\r\nnpm http GET https://registry.npmjs.org/juwai-lint-cfg\r\nnpm http 404 https://registry.npmjs.org/juwai-lint-cfg\r\nnpm ERR! TypeError: Object.keys called on non-object\r\nnpm ERR!     at Function.keys (native)\r\nnpm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)\r\nnpm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10\r\nnpm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)\r\nnpm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7\r\nnpm ERR!     at Object.oncomplete (fs.js:108:15)\r\nnpm ERR! If you need help, you may report this log at:\r\nnpm ERR!     <http://github.com/isaacs/npm/issues>\r\nnpm ERR! or email it to:\r\nnpm ERR!     <npm-@googlegroups.com>\r\n\r\nnpm ERR! System Linux 2.6.32-431.3.1.el6.x86_64\r\nnpm ERR! command \"node\" \"/usr/bin/npm\" \"install\"\r\nnpm ERR! cwd /home/vagrant/test\r\nnpm ERR! node -v v0.10.42\r\nnpm ERR! npm -v 1.3.6\r\nnpm ERR! type called_on_non_object\r\nnpm ERR!\r\nnpm ERR! Additional logging details can be found in:\r\nnpm ERR!     /home/vagrant/test/npm-debug.log\r\nnpm ERR! not ok code 0\r\n```\r\n\r\nThis is my package.json content:\r\n\r\n```json\r\n{\r\n  \"private\": true,\r\n  \"dependencies\": {\r\n    \"juwai-lint-cfg\": \"juwai/juwai-lint-cfg\"\r\n  }\r\n}\r\n```\r\n\r\nSo my question is what's the difference between these two npm package installation?"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13166",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13166/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13166/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13166/events",
    "html_url": "https://github.com/npm/npm/issues/13166",
    "id": 162047869,
    "number": 13166,
    "title": "npm ERR! Error: EPERM: operation not permitted, open ",
    "user": {
      "login": "furnaceX",
      "id": 11638022,
      "avatar_url": "https://avatars.githubusercontent.com/u/11638022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/furnaceX",
      "html_url": "https://github.com/furnaceX",
      "followers_url": "https://api.github.com/users/furnaceX/followers",
      "following_url": "https://api.github.com/users/furnaceX/following{/other_user}",
      "gists_url": "https://api.github.com/users/furnaceX/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/furnaceX/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/furnaceX/subscriptions",
      "organizations_url": "https://api.github.com/users/furnaceX/orgs",
      "repos_url": "https://api.github.com/users/furnaceX/repos",
      "events_url": "https://api.github.com/users/furnaceX/events{/privacy}",
      "received_events_url": "https://api.github.com/users/furnaceX/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-23T23:47:27Z",
    "updated_at": "2016-06-23T23:47:27Z",
    "closed_at": null,
    "body": "Trying to install Ionic using npm. This is similar to many others, but I haven't seen this error with **OPEN**.\r\n\r\nWindows 7 x64.  I've tried node v0.8, v0.10.38, v6.2.2.  All have the exact same error.\r\nI've tried different versions of ionic.\r\nI've uninstall everything.  I've done cache cleans.  I've moved directories.  I've used Admin consoles. \r\n\r\nAny ideas would be greatly appreciated!\r\n\r\n`C:\\N>npm install -g ionic@beta\r\nnpm ERR! tar.unpack untar error C:\\Users\\Scott\\AppData\\Roaming\\npm-cache\\ionic\\2\r\n.0.0-beta.32\\package.tgz\r\nnpm ERR! Windows_NT 6.1.7601\r\nnpm ERR! argv \"C:\\\\N\\\\node.exe\" \"C:\\\\N\\\\node_modules\\\\npm\\\\bin\\\\npm-cli.js\" \"ins\r\ntall\" \"-g\" \"ionic@beta\"\r\nnpm ERR! node v6.2.2\r\nnpm ERR! npm  v3.9.5\r\nnpm ERR! path c:\\npm\\temp\\npm-5168-46f40d44\\unpack-079d2c3a\\node_modules\\ionic-a\r\npp-lib\\node_modules\\cordova-lib\\node_modules\\cordova-js\\node_modules\\browserify\\\r\nnode_modules\\browser-pack\\node_modules\\combine-source-map\\node_modules\\source-ma\r\np\\build\\prefix-source-map.jsm\r\n**npm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall open**\r\n\r\nnpm ERR! Error: EPERM: operation not permitted, open 'c:\\npm\\temp\\npm-5168-46f40\r\nd44\\unpack-079d2c3a\\node_modules\\ionic-app-lib\\node_modules\\cordova-lib\\node_mod\r\nules\\cordova-js\\node_modules\\browserify\\node_modules\\browser-pack\\node_modules\\c\r\nombine-source-map\\node_modules\\source-map\\build\\prefix-source-map.jsm'\r\nnpm ERR!     at Error (native)\r\nnpm ERR!  { Error: EPERM: operation not permitted, open 'c:\\npm\\temp\\npm-5168-46\r\nf40d44\\unpack-079d2c3a\\node_modules\\ionic-app-lib\\node_modules\\cordova-lib\\node_\r\nmodules\\cordova-js\\node_modules\\browserify\\node_modules\\browser-pack\\node_module\r\ns\\combine-source-map\\node_modules\\source-map\\build\\prefix-source-map.jsm'\r\nnpm ERR!     at Error (native)\r\nnpm ERR!   errno: -4048,\r\nnpm ERR!   code: 'EPERM',\r\nnpm ERR!   syscall: 'open',\r\nnpm ERR!   path: 'c:\\\\npm\\\\temp\\\\npm-5168-46f40d44\\\\unpack-079d2c3a\\\\node_module\r\ns\\\\ionic-app-lib\\\\node_modules\\\\cordova-lib\\\\node_modules\\\\cordova-js\\\\node_modu\r\nles\\\\browserify\\\\node_modules\\\\browser-pack\\\\node_modules\\\\combine-source-map\\\\n\r\node_modules\\\\source-map\\\\build\\\\prefix-source-map.jsm' }\r\nnpm ERR!\r\nnpm ERR! Please try running this command again as root/Administrator.\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     C:\\N\\npm-debug.log`"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13165",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13165/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13165/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13165/events",
    "html_url": "https://github.com/npm/npm/issues/13165",
    "id": 162043035,
    "number": 13165,
    "title": "outdated runs prepublish script",
    "user": {
      "login": "doug-wade",
      "id": 3477707,
      "avatar_url": "https://avatars.githubusercontent.com/u/3477707?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/doug-wade",
      "html_url": "https://github.com/doug-wade",
      "followers_url": "https://api.github.com/users/doug-wade/followers",
      "following_url": "https://api.github.com/users/doug-wade/following{/other_user}",
      "gists_url": "https://api.github.com/users/doug-wade/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/doug-wade/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/doug-wade/subscriptions",
      "organizations_url": "https://api.github.com/users/doug-wade/orgs",
      "repos_url": "https://api.github.com/users/doug-wade/repos",
      "events_url": "https://api.github.com/users/doug-wade/events{/privacy}",
      "received_events_url": "https://api.github.com/users/doug-wade/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-23T23:06:14Z",
    "updated_at": "2016-06-23T23:06:14Z",
    "closed_at": null,
    "body": "I don't really get this one\r\n\r\n```\r\ndougwade packages/react-server-integration-tests ‹use-babel-preset-in-cli*› » npm outdated\r\n\r\n> react-server@0.3.2 prepublish /Users/doug.wade/code/react-server/packages/react-server\r\n> gulp build\r\n\r\n(node:2951) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.\r\n[15:50:15] Using gulpfile ~/code/react-server/packages/react-server/gulpfile.js\r\n[15:50:15] Starting 'compileClient'...\r\n[15:50:15] Starting 'compileServer'...\r\n[15:50:15] Finished 'compileServer' after 79 ms\r\n[15:50:15] Finished 'compileClient' after 98 ms\r\n[15:50:15] Starting 'compile'...\r\n[15:50:15] Finished 'compile' after 14 μs\r\n[15:50:15] Starting 'build'...\r\n[15:50:15] Finished 'build' after 3.4 μs\r\n\r\n> react-server-cli@0.3.2 prepublish /Users/doug.wade/code/react-server/packages/react-server-cli\r\n> gulp\r\n\r\n[15:50:16] Requiring external module babel-register\r\n(node:2952) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.\r\n[15:50:17] Using gulpfile ~/code/react-server/packages/react-server-cli/gulpfile.babel.js\r\n[15:50:17] Starting 'default'...\r\n[15:50:18] Finished 'default' after 718 ms\r\nPackage     Current  Wanted  Latest  Location\r\nreact        0.14.8  0.14.8  15.1.0  react-server-integration-tests\r\nreact-dom    0.14.8  0.14.8  15.1.0  react-server-integration-tests\r\nsuperagent    1.2.0   1.2.0   2.0.0  react-server-integration-tests\r\n```"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13164",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13164/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13164/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13164/events",
    "html_url": "https://github.com/npm/npm/issues/13164",
    "id": 162012967,
    "number": 13164,
    "title": "Trying to update my npm published package",
    "user": {
      "login": "Subomi",
      "id": 5220101,
      "avatar_url": "https://avatars.githubusercontent.com/u/5220101?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Subomi",
      "html_url": "https://github.com/Subomi",
      "followers_url": "https://api.github.com/users/Subomi/followers",
      "following_url": "https://api.github.com/users/Subomi/following{/other_user}",
      "gists_url": "https://api.github.com/users/Subomi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Subomi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Subomi/subscriptions",
      "organizations_url": "https://api.github.com/users/Subomi/orgs",
      "repos_url": "https://api.github.com/users/Subomi/repos",
      "events_url": "https://api.github.com/users/Subomi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Subomi/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-23T20:14:52Z",
    "updated_at": "2016-06-25T21:26:29Z",
    "closed_at": null,
    "body": "How do i get to do this? do i republish? \r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13162",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13162/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13162/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13162/events",
    "html_url": "https://github.com/npm/npm/issues/13162",
    "id": 161967064,
    "number": 13162,
    "title": "npm issues",
    "user": {
      "login": "spark78",
      "id": 10963580,
      "avatar_url": "https://avatars.githubusercontent.com/u/10963580?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/spark78",
      "html_url": "https://github.com/spark78",
      "followers_url": "https://api.github.com/users/spark78/followers",
      "following_url": "https://api.github.com/users/spark78/following{/other_user}",
      "gists_url": "https://api.github.com/users/spark78/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/spark78/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/spark78/subscriptions",
      "organizations_url": "https://api.github.com/users/spark78/orgs",
      "repos_url": "https://api.github.com/users/spark78/repos",
      "events_url": "https://api.github.com/users/spark78/events{/privacy}",
      "received_events_url": "https://api.github.com/users/spark78/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-23T16:32:09Z",
    "updated_at": "2016-06-25T21:48:17Z",
    "closed_at": null,
    "body": "heelo I have this problem could you helop me please.\r\n\r\n\r\n```\r\nDébut de l'installation\r\nVersion actuelle : v4.2.1\r\nReading package lists...\r\nBuilding dependency tree...\r\nReading state information...\r\npn533 déjà en blacklist\r\nOk, version suffisante\r\nnpm ERR! tar.unpack untar error /root/.npm/har-validator/2.0.6/package.tgz\r\nnpm ERR! tar.unpack untar error /root/.npm/node-uuid/1.4.7/package.tgz\r\nnpm ERR! tar.unpack untar error /root/.npm/readable-stream/2.1.4/package.tgz\r\nnpm ERR! tar.unpack untar error /root/.npm/es6-symbol/3.1.0/package.tgz\r\nnpm ERR! tar.unpack untar error /root/.npm/minimist/0.0.8/package.tgz\r\nnpm WARN locking Error: ENOENT: no such file or directory, open '/root/.npm/_locks/wrappy-018fc02e04052233.lock'\r\nnpm WARN locking     at Error (native)\r\nnpm WARN locking  /root/.npm/_locks/wrappy-018fc02e04052233.lock failed { [Error: ENOENT: no such file or directory, open '/root/.npm/_locks/wrappy-018fc02e04052233.lock']\r\nnpm WARN locking   errno: -2,\r\nnpm WARN locking   code: 'ENOENT',\r\nnpm WARN locking   syscall: 'open',\r\nnpm WARN locking   path: '/root/.npm/_locks/wrappy-018fc02e04052233.lock' }\r\nnpm ERR! Linux 4.4.13+\r\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"install\" \"--unsafe-perm\" \"https://github.com/athombv/node-nfc\"\r\nnpm ERR! node v4.2.1\r\nnpm ERR! npm  v2.14.7\r\nnpm ERR! Attempt to unlock /var/www/html/plugins/nfc/node/node_modules/nfc/node_modules/node-gyp/node_modules/rimraf/node_modules/glob/node_modules/once/node_modules/wrappy, which hasn't been locked\r\nnpm ERR!\r\nnpm ERR! If you need help, you may report this error at:\r\nnpm ERR!     <https://github.com/npm/npm/issues>\r\nnpm WARN locking Error: ENOENT: no such file or directory, open '/root/.npm/_locks/wrappy-377ae6cb0531a63f.lock'\r\nnpm WARN locking     at Error (native)\r\nnpm WARN locking  /root/.npm/_locks/wrappy-377ae6cb0531a63f.lock failed { [Error: ENOENT: no such file or directory, open '/root/.npm/_locks/wrappy-377ae6cb0531a63f.lock']\r\nnpm WARN locking   errno: -2,\r\nnpm WARN locking   code: 'ENOENT',\r\nnpm WARN locking   syscall: 'open',\r\nnpm WARN locking   path: '/root/.npm/_locks/wrappy-377ae6cb0531a63f.lock' }\r\nnpm ERR! Linux 4.4.13+\r\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"install\" \"--unsafe-perm\" \"https://github.com/athombv/node-nfc\"\r\nnpm ERR! node v4.2.1\r\nnpm ERR! npm  v2.14.7\r\nnpm ERR! Attempt to unlock /var/www/html/plugins/nfc/node/node_modules/nfc/node_modules/node-gyp/node_modules/rimraf/node_modules/glob/node_modules/inflight/node_modules/wrappy, which hasn't been locked\r\nnpm ERR!\r\n```"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13161",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13161/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13161/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13161/events",
    "html_url": "https://github.com/npm/npm/issues/13161",
    "id": 161955315,
    "number": 13161,
    "title": "`npm install` output messy code",
    "user": {
      "login": "UniFreak",
      "id": 7945546,
      "avatar_url": "https://avatars.githubusercontent.com/u/7945546?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/UniFreak",
      "html_url": "https://github.com/UniFreak",
      "followers_url": "https://api.github.com/users/UniFreak/followers",
      "following_url": "https://api.github.com/users/UniFreak/following{/other_user}",
      "gists_url": "https://api.github.com/users/UniFreak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/UniFreak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/UniFreak/subscriptions",
      "organizations_url": "https://api.github.com/users/UniFreak/orgs",
      "repos_url": "https://api.github.com/users/UniFreak/repos",
      "events_url": "https://api.github.com/users/UniFreak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/UniFreak/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-23T15:40:27Z",
    "updated_at": "2016-06-26T13:58:22Z",
    "closed_at": null,
    "body": "I'm in Windows7 64bit, system language is Chinese.\r\n\r\nevery time when I'm trying to install something , say jshint, output like this:\r\n\r\n![qq 20160623233657](https://cloud.githubusercontent.com/assets/7945546/16309567/bdb8c5ac-399b-11e6-9d69-f1fc9c5b7d69.png)\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13160",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13160/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13160/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13160/events",
    "html_url": "https://github.com/npm/npm/issues/13160",
    "id": 161947721,
    "number": 13160,
    "title": "NPM search error",
    "user": {
      "login": "HughGrant",
      "id": 752577,
      "avatar_url": "https://avatars.githubusercontent.com/u/752577?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HughGrant",
      "html_url": "https://github.com/HughGrant",
      "followers_url": "https://api.github.com/users/HughGrant/followers",
      "following_url": "https://api.github.com/users/HughGrant/following{/other_user}",
      "gists_url": "https://api.github.com/users/HughGrant/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HughGrant/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HughGrant/subscriptions",
      "organizations_url": "https://api.github.com/users/HughGrant/orgs",
      "repos_url": "https://api.github.com/users/HughGrant/repos",
      "events_url": "https://api.github.com/users/HughGrant/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HughGrant/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-06-23T15:11:14Z",
    "updated_at": "2016-06-26T13:57:58Z",
    "closed_at": null,
    "body": "The following is the error message, anyone knows this issue?\r\n\r\n```\r\nnpm WARN Building the local index for the first time, please be patient\r\nnpm ERR! Darwin 15.5.0\r\nnpm ERR! argv \"/usr/local/Cellar/node/6.2.0/bin/node\" \"/usr/local/bin/npm\" \"--registry=https://registry.npm.taobao.org\" \"--cache=/Users/tuwenmin/.npm/.cache/cnpm\" \"--disturl=https://npm.taobao.org/dist\" \"--userconfig=/Users/tuwenmin/.cnpmrc\" \"search\" \"webpack\"\r\nnpm ERR! node v6.2.0\r\nnpm ERR! npm  v3.10.2\r\nnpm ERR! code E200\r\n\r\nnpm ERR! true true: -/all\r\nnpm ERR! \r\nnpm ERR! If you need help, you may report this error at:\r\nnpm ERR!     <https://github.com/npm/npm/issues>\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     /Users/tuwenmin/npm-debug.log\r\n```"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13159",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13159/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13159/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13159/events",
    "html_url": "https://github.com/npm/npm/issues/13159",
    "id": 161915489,
    "number": 13159,
    "title": "Error installing atom-typescript --> SELF_SIGNED_CERT_IN_CHAIN",
    "user": {
      "login": "rhuynh01",
      "id": 20097610,
      "avatar_url": "https://avatars.githubusercontent.com/u/20097610?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rhuynh01",
      "html_url": "https://github.com/rhuynh01",
      "followers_url": "https://api.github.com/users/rhuynh01/followers",
      "following_url": "https://api.github.com/users/rhuynh01/following{/other_user}",
      "gists_url": "https://api.github.com/users/rhuynh01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rhuynh01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rhuynh01/subscriptions",
      "organizations_url": "https://api.github.com/users/rhuynh01/orgs",
      "repos_url": "https://api.github.com/users/rhuynh01/repos",
      "events_url": "https://api.github.com/users/rhuynh01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rhuynh01/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-23T12:53:00Z",
    "updated_at": "2016-06-23T12:53:00Z",
    "closed_at": null,
    "body": "Hi,\r\n\r\nI tried to install atom-typescript package but I kept getting this error \"SELF_SIGNED_CERT_IN_CHAIN\"\r\n\r\nI have upgraded to the latest version of Node.js (v6.2.2) and npm version 3.9.5\r\n\r\nI also tried \r\nnpm config set ca=\"\"\r\nor \r\nnpm config delete ca\r\n\r\nI still does not work.  Any help would be greatly appreciated.\r\n\r\nPS:  I tried to install typescript inside atom IDE but still does not work.  Below is my npm-debug.log\r\n\r\nThanks in advace\r\n\r\n[npm-debug.txt](https://github.com/npm/npm/files/329956/npm-debug.txt)\r\n"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13158",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13158/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13158/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13158/events",
    "html_url": "https://github.com/npm/npm/issues/13158",
    "id": 161842844,
    "number": 13158,
    "title": "Unable to install browser sync on Windows 7",
    "user": {
      "login": "nikhilrwagh",
      "id": 20079710,
      "avatar_url": "https://avatars.githubusercontent.com/u/20079710?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nikhilrwagh",
      "html_url": "https://github.com/nikhilrwagh",
      "followers_url": "https://api.github.com/users/nikhilrwagh/followers",
      "following_url": "https://api.github.com/users/nikhilrwagh/following{/other_user}",
      "gists_url": "https://api.github.com/users/nikhilrwagh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nikhilrwagh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nikhilrwagh/subscriptions",
      "organizations_url": "https://api.github.com/users/nikhilrwagh/orgs",
      "repos_url": "https://api.github.com/users/nikhilrwagh/repos",
      "events_url": "https://api.github.com/users/nikhilrwagh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nikhilrwagh/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-23T05:28:24Z",
    "updated_at": "2016-06-23T05:28:24Z",
    "closed_at": null,
    "body": "Hi Guys, \r\nCan please help me out installing the browser sync on windows 7.\r\nI tried running the browser sync command in CMD prompt logging in as a administrator but it wont worked. Following are the errors i am facing out currently.\r\n\r\nC:\\Windows\\system32>npm install -g browser-sync\r\nnpm ERR! Windows_NT 6.1.7601\r\nnpm ERR! argv \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\\r\nnode_modules\\\\npm\\\\bin\\\\npm-cli.js\" \"install\" \"-g\" \"browser-sync\"\r\nnpm ERR! node v4.4.5\r\nnpm ERR! npm  v2.15.5\r\nnpm ERR! code ECONNREFUSED\r\nnpm ERR! errno ECONNREFUSED\r\nnpm ERR! syscall connect\r\n\r\nnpm ERR! Error: connect ECONNREFUSED 23.235.39.162:443\r\nnpm ERR!     at Object.exports._errnoException (util.js:870:11)\r\nnpm ERR!     at exports._exceptionWithHostPort (util.js:893:20)\r\nnpm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)\r\nnpm ERR!  { [Error: connect ECONNREFUSED 23.235.39.162:443]\r\nnpm ERR!   code: 'ECONNREFUSED',\r\nnpm ERR!   errno: 'ECONNREFUSED',\r\nnpm ERR!   syscall: 'connect',\r\nnpm ERR!   address: '23.235.39.162',\r\nnpm ERR!   port: 443 }\r\nnpm ERR!\r\nnpm ERR! If you are behind a proxy, please make sure that the\r\nnpm ERR! 'proxy' config is set properly.  See: 'npm help config'\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     C:\\Windows\\system32\\npm-debug.log\r\n\r\nC:\\Windows\\system32>echo %http_proxy%\r\n%http_proxy%\r\n\r\nC:\\Windows\\system32>"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13157",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13157/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13157/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13157/events",
    "html_url": "https://github.com/npm/npm/issues/13157",
    "id": 161820874,
    "number": 13157,
    "title": "Error to install cordova in mac os x El Captain - sudo npm install -g cordova",
    "user": {
      "login": "emoryr",
      "id": 4583040,
      "avatar_url": "https://avatars.githubusercontent.com/u/4583040?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/emoryr",
      "html_url": "https://github.com/emoryr",
      "followers_url": "https://api.github.com/users/emoryr/followers",
      "following_url": "https://api.github.com/users/emoryr/following{/other_user}",
      "gists_url": "https://api.github.com/users/emoryr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/emoryr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/emoryr/subscriptions",
      "organizations_url": "https://api.github.com/users/emoryr/orgs",
      "repos_url": "https://api.github.com/users/emoryr/repos",
      "events_url": "https://api.github.com/users/emoryr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/emoryr/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-23T01:21:21Z",
    "updated_at": "2016-06-23T01:21:21Z",
    "closed_at": null,
    "body": "npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\r\n/usr/local/lib\r\n└── (empty)\r\n\r\nnpm ERR! Darwin 15.5.0\r\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"install\" \"-g\" \"cordova\"\r\nnpm ERR! node v6.2.2\r\nnpm ERR! npm  v3.9.5\r\nnpm ERR! path /usr/local/lib/node_modules/.staging/abbrev-ef9cc920\r\nnpm ERR! code ENOENT\r\nnpm ERR! errno -2\r\nnpm ERR! syscall rename\r\n\r\nnpm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'\r\nnpm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'\r\nnpm ERR! enoent This is most likely not a problem with npm itself\r\nnpm ERR! enoent and is related to npm not being able to find a file.\r\nnpm ERR! enoent \r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     /Users/emoryfreitas/npm-debug.log\r\nnpm ERR! code 1"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13156",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13156/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13156/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13156/events",
    "html_url": "https://github.com/npm/npm/pull/13156",
    "id": 161812677,
    "number": 13156,
    "title": "[docs] Change .md reference in install.js",
    "user": {
      "login": "sheerun",
      "id": 292365,
      "avatar_url": "https://avatars.githubusercontent.com/u/292365?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sheerun",
      "html_url": "https://github.com/sheerun",
      "followers_url": "https://api.github.com/users/sheerun/followers",
      "following_url": "https://api.github.com/users/sheerun/following{/other_user}",
      "gists_url": "https://api.github.com/users/sheerun/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sheerun/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sheerun/subscriptions",
      "organizations_url": "https://api.github.com/users/sheerun/orgs",
      "repos_url": "https://api.github.com/users/sheerun/repos",
      "events_url": "https://api.github.com/users/sheerun/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sheerun/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-22T23:56:43Z",
    "updated_at": "2016-06-22T23:56:43Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/npm/npm/pulls/13156",
      "html_url": "https://github.com/npm/npm/pull/13156",
      "diff_url": "https://github.com/npm/npm/pull/13156.diff",
      "patch_url": "https://github.com/npm/npm/pull/13156.patch"
    },
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13155",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13155/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13155/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13155/events",
    "html_url": "https://github.com/npm/npm/issues/13155",
    "id": 161807670,
    "number": 13155,
    "title": "ECONNRESET/ETIMEOUT should display URL",
    "user": {
      "login": "tlhunter",
      "id": 551402,
      "avatar_url": "https://avatars.githubusercontent.com/u/551402?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tlhunter",
      "html_url": "https://github.com/tlhunter",
      "followers_url": "https://api.github.com/users/tlhunter/followers",
      "following_url": "https://api.github.com/users/tlhunter/following{/other_user}",
      "gists_url": "https://api.github.com/users/tlhunter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tlhunter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tlhunter/subscriptions",
      "organizations_url": "https://api.github.com/users/tlhunter/orgs",
      "repos_url": "https://api.github.com/users/tlhunter/repos",
      "events_url": "https://api.github.com/users/tlhunter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tlhunter/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-06-22T23:13:47Z",
    "updated_at": "2016-06-22T23:13:47Z",
    "closed_at": null,
    "body": "We get tons of ECONNRESET errors on our build servers. Tracking down why the errors happen has been a real headscratcher.\r\n\r\nIdeally, any time NPM encounters an ECONNRESET or an ETIMEOUT error, it should display whatever URL it was attempting to grab which triggered the error. Otherwise, the existing error logs don't provide many clues:\r\n\r\n```\r\n[23:03:34][npm install] npm ERR! node v4.2.4\r\n[23:03:34][npm install] npm ERR! npm  v3.9.6\r\n[23:03:34][npm install] npm ERR! code ECONNRESET\r\n[23:03:34][npm install] npm ERR! errno ECONNRESET\r\n[23:03:34][npm install] npm ERR! syscall read\r\n[23:03:34][npm install] \r\n[23:03:34][npm install] npm ERR! network read ECONNRESET\r\n[23:03:34][npm install] npm ERR! network This is most likely not a problem with npm itself\r\n[23:03:34][npm install] npm ERR! network and is related to network connectivity.\r\n[23:03:34][npm install] npm ERR! network In most cases you are behind a proxy or have bad network settings.\r\n[23:03:34][npm install] npm ERR! network \r\n[23:03:34][npm install] npm ERR! network If you are behind a proxy, please make sure that the\r\n[23:03:34][npm install] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'\r\n[23:03:35][npm install] npm ERR! Linux 4.4.2\r\n[23:03:35][npm install] npm ERR! argv \"/var/teamcity/build-agent/system/asdf/v4.2.4/bin/node\" \"/var/teamcity/build-agent/system/asdf/v4.2.4/bin/npm\" \"install\"\r\n[23:03:35][npm install] npm ERR! node v4.2.4\r\n[23:03:35][npm install] npm ERR! npm  v3.9.6\r\n[23:03:35][npm install] npm ERR! code ECONNRESET\r\n[23:03:35][npm install] npm ERR! errno ECONNRESET\r\n[23:03:35][npm install] npm ERR! syscall read\r\n[23:03:35][npm install] \r\n[23:03:35][npm install] npm ERR! network read ECONNRESET\r\n[23:03:35][npm install] npm ERR! network This is most likely not a problem with npm itself\r\n[23:03:35][npm install] npm ERR! network and is related to network connectivity.\r\n[23:03:35][npm install] npm ERR! network In most cases you are behind a proxy or have bad network settings.\r\n[23:03:35][npm install] npm ERR! network \r\n[23:03:35][npm install] npm ERR! network If you are behind a proxy, please make sure that the\r\n[23:03:35][npm install] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'\r\n[23:03:36][npm install] npm ERR! Linux 4.4.2\r\n[23:03:36][npm install] npm ERR! argv \"/var/teamcity/build-agent/system/asdf/v4.2.4/bin/node\" \"/var/teamcity/build-agent/system/asdf/v4.2.4/bin/npm\" \"install\"\r\n```"
  },
  {
    "url": "https://api.github.com/repos/npm/npm/issues/13153",
    "repository_url": "https://api.github.com/repos/npm/npm",
    "labels_url": "https://api.github.com/repos/npm/npm/issues/13153/labels{/name}",
    "comments_url": "https://api.github.com/repos/npm/npm/issues/13153/comments",
    "events_url": "https://api.github.com/repos/npm/npm/issues/13153/events",
    "html_url": "https://github.com/npm/npm/issues/13153",
    "id": 161746186,
    "number": 13153,
    "title": "unable to \"install npm\" permission ERROR",
    "user": {
      "login": "ScofeeZ",
      "id": 19142410,
      "avatar_url": "https://avatars.githubusercontent.com/u/19142410?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ScofeeZ",
      "html_url": "https://github.com/ScofeeZ",
      "followers_url": "https://api.github.com/users/ScofeeZ/followers",
      "following_url": "https://api.github.com/users/ScofeeZ/following{/other_user}",
      "gists_url": "https://api.github.com/users/ScofeeZ/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ScofeeZ/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ScofeeZ/subscriptions",
      "organizations_url": "https://api.github.com/users/ScofeeZ/orgs",
      "repos_url": "https://api.github.com/users/ScofeeZ/repos",
      "events_url": "https://api.github.com/users/ScofeeZ/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ScofeeZ/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/npm/npm/labels/git",
        "name": "git",
        "color": "DA655E"
      },
      {
        "url": "https://api.github.com/repos/npm/npm/labels/support",
        "name": "support",
        "color": "000000"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2016-06-22T17:55:08Z",
    "updated_at": "2016-06-25T20:05:18Z",
    "closed_at": null,
    "body": "Hi everyone, i just wanted to install Foundation 6 and followed step to do.\r\nI have to say i already installed npm in global on my ubuntu 16.04, same for bower\r\n\r\n**here you have the result of my issue when i type \"npm install\" in my project folder:**\r\n\r\n```\r\n> npm install\r\nnpm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.\r\nnpm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:\r\nnpm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'\r\nnpm ERR! git rev-list -n1 4.0: \r\nnpm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.\r\nnpm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:\r\nnpm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'\r\nnpm ERR! git rev-list -n1 4.0: \r\nnpm ERR! git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Clonage dans le dépôt nu '/home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb'\r\nnpm ERR! git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Permission denied (publickey).\r\nnpm ERR! git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: fatal: Could not read from remote repository.\r\nnpm ERR! git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: \r\nnpm ERR! git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Please make sure you have the correct access rights\r\nnpm ERR! git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: and the repository exists.\r\nnpm ERR! Linux 4.4.0-24-generic\r\nnpm ERR! argv \"/usr/bin/nodejs\" \"/usr/local/bin/npm\" \"install\"\r\nnpm ERR! node v4.2.6\r\nnpm ERR! npm  v3.5.2\r\nnpm ERR! code 128\r\n\r\nnpm ERR! Command failed: git clone --template=/home/scofeez/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb\r\nnpm ERR! Clonage dans le dépôt nu '/home/scofeez/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb'\r\nnpm ERR! Permission denied (publickey).\r\nnpm ERR! fatal: Could not read from remote repository.\r\nnpm ERR! \r\nnpm ERR! Please make sure you have the correct access rights\r\nnpm ERR! and the repository exists.\r\nnpm ERR! \r\nnpm ERR! \r\nnpm ERR! If you need help, you may report this error at:\r\nnpm ERR!     <https://github.com/npm/npm/issues>\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     /home/scofeez/mr_robot/month_two/www/ViTAE/npm-debug.log\r\n```\r\n\r\n**and there you have the log lines about the following issue:**\r\nhttp://pastebin.com/RGyUsJvr\r\n\r\nif you can help me.. it would be a lot for me guys ;)\r\n**THANK YOU !**"
  }
];